internal class MockException() : Exception("MockError");